// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anime.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAnime = `-- name: ArchiveAnime :exec
UPDATE anime SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) ArchiveAnime(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, archiveAnime, id)
	return err
}

const countFilteredAnime = `-- name: CountFilteredAnime :one
SELECT COUNT(*) FROM anime
WHERE
    ($1::text = '' OR LOWER(title) LIKE LOWER('%' || $1 || '%'))
    AND ($2::text = '' OR LOWER(genre) LIKE LOWER('%' || $2 || '%'))
    AND ($3::text = '' OR status = $3)
    AND ($4::timestamp IS NULL OR release_date >= $4)
    AND ($5::timestamp IS NULL OR release_date <= $5)
    AND deleted_at IS NULL
`

type CountFilteredAnimeParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 pgtype.Timestamp
	Column5 pgtype.Timestamp
}

func (q *Queries) CountFilteredAnime(ctx context.Context, arg CountFilteredAnimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredAnime,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnime = `-- name: CreateAnime :one
INSERT INTO anime (title, genre, episodes, status, image_url, release_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, genre, episodes, status, created_at, image_url, release_date, deleted_at
`

type CreateAnimeParams struct {
	Title       string
	Genre       string
	Episodes    int32
	Status      string
	ImageUrl    string
	ReleaseDate pgtype.Timestamp
}

func (q *Queries) CreateAnime(ctx context.Context, arg CreateAnimeParams) (Anime, error) {
	row := q.db.QueryRow(ctx, createAnime,
		arg.Title,
		arg.Genre,
		arg.Episodes,
		arg.Status,
		arg.ImageUrl,
		arg.ReleaseDate,
	)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Genre,
		&i.Episodes,
		&i.Status,
		&i.CreatedAt,
		&i.ImageUrl,
		&i.ReleaseDate,
		&i.DeletedAt,
	)
	return i, err
}

const filterAnimePaginated = `-- name: FilterAnimePaginated :many
SELECT id, title, genre, episodes, status, created_at, image_url, release_date, deleted_at FROM anime
WHERE
    ($1::text = '' OR LOWER(title) LIKE LOWER('%' || $1 || '%'))
    AND ($2::text = '' OR LOWER(genre) LIKE LOWER('%' || $2 || '%'))
    AND ($3::text = '' OR status = $3)
    AND ($4::timestamp IS NULL OR release_date >= $4)
    AND ($5::timestamp IS NULL OR release_date <= $5)
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type FilterAnimePaginatedParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 pgtype.Timestamp
	Column5 pgtype.Timestamp
	Limit   int32
	Offset  int32
}

func (q *Queries) FilterAnimePaginated(ctx context.Context, arg FilterAnimePaginatedParams) ([]Anime, error) {
	rows, err := q.db.Query(ctx, filterAnimePaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anime
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Genre,
			&i.Episodes,
			&i.Status,
			&i.CreatedAt,
			&i.ImageUrl,
			&i.ReleaseDate,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnime = `-- name: GetAnime :one
SELECT id, title, genre, episodes, status, created_at, image_url, release_date, deleted_at FROM anime WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnime(ctx context.Context, id int32) (Anime, error) {
	row := q.db.QueryRow(ctx, getAnime, id)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Genre,
		&i.Episodes,
		&i.Status,
		&i.CreatedAt,
		&i.ImageUrl,
		&i.ReleaseDate,
		&i.DeletedAt,
	)
	return i, err
}

const listAnime = `-- name: ListAnime :many
SELECT id, title, genre, episodes, status, created_at, image_url, release_date, deleted_at FROM anime WHERE  deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListAnime(ctx context.Context) ([]Anime, error) {
	rows, err := q.db.Query(ctx, listAnime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anime
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Genre,
			&i.Episodes,
			&i.Status,
			&i.CreatedAt,
			&i.ImageUrl,
			&i.ReleaseDate,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnime = `-- name: UpdateAnime :one
UPDATE anime
SET title = $2, genre = $3, episodes = $4, status = $5, image_url = $6, release_date = $7
WHERE id = $1
RETURNING id, title, genre, episodes, status, created_at, image_url, release_date, deleted_at
`

type UpdateAnimeParams struct {
	ID          int32
	Title       string
	Genre       string
	Episodes    int32
	Status      string
	ImageUrl    string
	ReleaseDate pgtype.Timestamp
}

func (q *Queries) UpdateAnime(ctx context.Context, arg UpdateAnimeParams) (Anime, error) {
	row := q.db.QueryRow(ctx, updateAnime,
		arg.ID,
		arg.Title,
		arg.Genre,
		arg.Episodes,
		arg.Status,
		arg.ImageUrl,
		arg.ReleaseDate,
	)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Genre,
		&i.Episodes,
		&i.Status,
		&i.CreatedAt,
		&i.ImageUrl,
		&i.ReleaseDate,
		&i.DeletedAt,
	)
	return i, err
}
