// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action_type, entity_type, entity_id)
VALUES ($1, $2, $3, $4)
`

type CreateAuditLogParams struct {
	UserID     int32
	ActionType string
	EntityType string
	EntityID   int32
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.ActionType,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.user_id, u.name AS user_name, al.action_type, al.entity_type, al.entity_id, al.created_at
FROM audit_logs al
JOIN users u ON al.user_id = u.id
ORDER BY al.created_at DESC
LIMIT 100
`

type ListAuditLogsRow struct {
	ID         int32
	UserID     int32
	UserName   string
	ActionType string
	EntityType string
	EntityID   int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAuditLogs(ctx context.Context) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.ActionType,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
