// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Anime struct {
	ID          int32
	Title       string
	Genre       string
	Episodes    int32
	Status      string
	CreatedAt   pgtype.Timestamp
	ImageUrl    string
	ReleaseDate pgtype.Timestamp
	DeletedAt   pgtype.Timestamptz
}

type AnimeStudio struct {
	AnimeID  int32
	StudioID int32
}

type AuditLog struct {
	ID         int32
	UserID     int32
	ActionType string
	EntityType string
	EntityID   int32
	CreatedAt  pgtype.Timestamptz
}

type ServiceAccount struct {
	ID         int32
	Name       string
	ApiKeyHash string
	CreatedAt  pgtype.Timestamptz
}

type Studio struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID                 int32
	Email              string
	Name               string
	PasswordHash       string
	Role               string
	MustChangePassword bool
	CreatedAt          pgtype.Timestamp
}
