// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_account.sql

package db

import (
	"context"
)

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (name, api_key_hash)
VALUES ($1, $2)
RETURNING id, name, api_key_hash, created_at
`

type CreateServiceAccountParams struct {
	Name       string
	ApiKeyHash string
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount, arg.Name, arg.ApiKeyHash)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServiceAcount = `-- name: DeleteServiceAcount :exec
DELETE FROM service_accounts WHERE id = $1
`

func (q *Queries) DeleteServiceAcount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteServiceAcount, id)
	return err
}

const getServiceAccountByKeyHash = `-- name: GetServiceAccountByKeyHash :one
SELECT id, name, api_key_hash, created_at FROM service_accounts WHERE api_key_hash = $1
`

func (q *Queries) GetServiceAccountByKeyHash(ctx context.Context, apiKeyHash string) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, getServiceAccountByKeyHash, apiKeyHash)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const listServiceAccounts = `-- name: ListServiceAccounts :many
SELECT id, name, api_key_hash, created_at FROM service_accounts ORDER BY created_at DESC
`

func (q *Queries) ListServiceAccounts(ctx context.Context) ([]ServiceAccount, error) {
	rows, err := q.db.Query(ctx, listServiceAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceAccount
	for rows.Next() {
		var i ServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
