// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: studio.sql

package db

import (
	"context"
)

const addStudioToAnime = `-- name: AddStudioToAnime :exec
INSERT INTO anime_studios (anime_id, studio_id)
VALUES ($1, $2)
`

type AddStudioToAnimeParams struct {
	AnimeID  int32
	StudioID int32
}

func (q *Queries) AddStudioToAnime(ctx context.Context, arg AddStudioToAnimeParams) error {
	_, err := q.db.Exec(ctx, addStudioToAnime, arg.AnimeID, arg.StudioID)
	return err
}

const archiveStudio = `-- name: ArchiveStudio :exec
UPDATE studios SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) ArchiveStudio(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, archiveStudio, id)
	return err
}

const createStudio = `-- name: CreateStudio :one
INSERT INTO studios (name)
VALUES ($1)
RETURNING id, name, created_at, deleted_at
`

func (q *Queries) CreateStudio(ctx context.Context, name string) (Studio, error) {
	row := q.db.QueryRow(ctx, createStudio, name)
	var i Studio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAnimeStudios = `-- name: DeleteAnimeStudios :exec
DELETE FROM anime_studios WHERE anime_id = $1
`

func (q *Queries) DeleteAnimeStudios(ctx context.Context, animeID int32) error {
	_, err := q.db.Exec(ctx, deleteAnimeStudios, animeID)
	return err
}

const getStudio = `-- name: GetStudio :one
SELECT id, name, created_at, deleted_at FROM studios WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStudio(ctx context.Context, id int32) (Studio, error) {
	row := q.db.QueryRow(ctx, getStudio, id)
	var i Studio
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStudiosByAnime = `-- name: GetStudiosByAnime :many
SELECT s.id, s.name, s.created_at, s.deleted_at FROM studios s
JOIN anime_studios ans ON s.id = ans.studio_id
WHERE ans.anime_id = $1 
AND s.deleted_at IS NULL
`

func (q *Queries) GetStudiosByAnime(ctx context.Context, animeID int32) ([]Studio, error) {
	rows, err := q.db.Query(ctx, getStudiosByAnime, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Studio
	for rows.Next() {
		var i Studio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudios = `-- name: ListStudios :many
SELECT id, name, created_at, deleted_at FROM studios WHERE deleted_at IS NULL ORDER BY name ASC
`

func (q *Queries) ListStudios(ctx context.Context) ([]Studio, error) {
	rows, err := q.db.Query(ctx, listStudios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Studio
	for rows.Next() {
		var i Studio
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudioFromAnime = `-- name: RemoveStudioFromAnime :exec
DELETE FROM anime_studios
WHERE anime_id = $1 AND studio_id = $2
`

type RemoveStudioFromAnimeParams struct {
	AnimeID  int32
	StudioID int32
}

func (q *Queries) RemoveStudioFromAnime(ctx context.Context, arg RemoveStudioFromAnimeParams) error {
	_, err := q.db.Exec(ctx, removeStudioFromAnime, arg.AnimeID, arg.StudioID)
	return err
}
